### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by pdp2015** [Hendrik44/pi-weather-app#4]
Built the app for testing on simulator to see how its put together but it keeps crashing. To do with watch os. Any plans on a updated version?

Many Thanks

**Comment by Hendrik44** [comment]
I have to test it and will give you feedback soon. Yes it is planned to update the app but currently i have not  enough time to do it but Bugfixing should be no problem.

**Comment by pdp2015** [comment]
Have you tried to use the weather app to feth data from another source? like open weather? or is that not possible?

**Comment by Hendrik44** [comment]
Sorry but this is not the goal of this project. This app only works with a raspberrypi as a Server, which collecting sensor values inside rooms or outside. This isnt just a "normal" weather app fetching data from everywhere. The goal is to provide as accurately as possible sensor readings about the climate in individual rooms or even outdoors.

**Comment by Hendrik44** [comment]
I can't reproduce your crash. I testet it and the app runs without a crash, see screenshot. Do you setup the project correctly described in readme? Otherwise clone the updated version and try it again, but it is only a feature update so it should be no sense. 

<img width="892" alt="screen shot 2018-04-08 at 21 26 33" src="https://user-images.githubusercontent.com/4581596/38471610-b977f96e-3b73-11e8-98e6-892bcea4616f.png">

**Comment by Hendrik44** [comment]
No response for more than two weeks. Close
